twitter: "https://twitter.com/dmoscatelli95"
github: "https://github.com/davidemoscatelli"
instagram: "https://www.instagram.com/davide_moscatelli/"
linkedin: "https://it.linkedin.com/in/davide-moscatelli-6ba512193"
facebook: "https://www.facebook.com/davide.moscatelli.18"
youtube: ""
medium: ""
patreon: ""
paypal: ""
unsplash: ""
